name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build app
        run: |
          xcodebuild -project Flyt.xcodeproj \
            -scheme Flyt \
            -configuration Release \
            -derivedDataPath ./build \
            build

      - name: Verify build
        run: |
          APP_PATH="./build/Build/Products/Release/Flyt.app"
          if [ ! -d "$APP_PATH" ]; then
            echo "Error: App not found at $APP_PATH"
            exit 1
          fi
          echo "Build successful: Flyt.app created"
