name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer

      - name: Build app
        run: |
          xcodebuild -project Flyt.xcodeproj \
            -scheme Flyt \
            -configuration Release \
            -derivedDataPath ./build \
            build

      - name: Create app bundle
        run: |
          # ビルド成果物のパス
          APP_PATH="./build/Build/Products/Release/Flyt.app"

          # アプリが存在するか確認
          if [ ! -d "$APP_PATH" ]; then
            echo "Error: App not found at $APP_PATH"
            exit 1
          fi

          # ZIPファイルを作成
          cd ./build/Build/Products/Release
          zip -r Flyt.zip Flyt.app
          mv Flyt.zip ../../../../

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Flyt.zip
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
